=== 343GuiltySpark-04/DefaultChecklists/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Reentry Checklist schema",
    "type": "object",
    "additionalProperties": false,
    "required": ["Group", "Name", "ProjectName", "Side", "SortPriority", "Spacecraft", "Steps", "Images"],
    "properties": {
        "Group": {"type": "string"},
        "Name": {"type": "string"},
        "ProjectName": {"type": "string"},
        "Side": {
            "type": "integer",
            "minimum": 0,
            "maximum": 1
        },
        "SortPriority": {"type": "integer"},
        "Spacecraft": {
            "type": "integer",
            "minimum": 0,
            "maximum": 3
        },
        "Steps": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": ["Program", "SetID", "Text", "ToPosID", "Type"],
                "properties": {
                    "Program": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 3
                    },
                    "SetID": {
                        "type": "integer"
                    },
                    "Text": {
                        "type": "string"
                    },
                    "ToPosID": {
                        "type": "integer"
                    },
                    "Type": {
                        "type": "integer"
                    }
                }
            }
        },
        "Images": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Position": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["x", "y"],
                        "properties": {
                            "x": {
                                "type": "number"
                            },
                            "y": {
                                "type": "number"
                            }
                        }
                    },
                    "Size": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["x", "y"],
                        "properties": {
                            "x": {
                                "type": "number"
                            },
                            "y": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "checklistText": {
            "type": "string"
        }
    }
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/PoweredDescentP68/checklist.json
{
    "Group": "LUNAR DESCENT",
    "Name": "P68 - LANDING CONFIRMATION",
    "ProjectName": "PoweredDescentP68",
    "Side": 0,
    "SortPriority": 205,
    "Spacecraft": 1,
    "Steps": [],
    "Images": [],
    "checklistText": "LANDING CONFIRMATION PROGRAM (P68)\r\n\r\n1.\tIf not yet done, key V37E 68E\r\n\r\n2.\tFL V06 N43 - LM landing position\r\n\t\tR1 Latitude\tXXX.XX\u00c2\u00b0\r\n\t\tR2 Longitude\tXXX.XX\u00c2\u00b0\r\n\t\tR3 Altitude\t\tXXXX.X nm\r\n\r\n\tRecord LM landing position data.\r\n\r\n\tKey PRO\r\n\tP00 automatically started\r\n\r\nPanel 1:\r\n3.\tDES ENG CMD OVRD sw - OFF\r\n"
}

=== 343GuiltySpark-04/DefaultChecklists/Mercury/PrepPreFlight/checklist.json
{"Spacecraft":3,"ProjectName":"PrepPreFlight","Group":"PRE-FLIGHT","Name":"Pre-Flight","Side":0,"SortPriority":10,"checklistText":"1. All left panel fuses - NO. 1 POSITION\n2. Squib switch - OFF\n3. Auto retro jett switch - ARM\n4. ASCS switch - NORM\n5. RSCS switch - AUTO\n6. Gyro switch - GYRO NORM\n7. Manual fuel handle - PUSH IN\n8. Roll fuel handle - PUSH IN\n9. Yaw fuel handle - PUSH IN\n10. Pitch fuel handle - PUSH IN\n11. Retro delay switch - INST\n12. Photo lights switch - ON\n13. Cabin lights switch - BOTH\n14. TLM-LO freq switch - ON\n15. Rescue switch - AUTO\n16. Launch Contl switch - OFF\n17. Jett Tower Ring - IN\n18. Sep Capsule Ring - IN\n19. Retro Att switch - AUTO\n20. Fire Retro switch - GUARD\n21. Jett Retro switch - GUARD\n22. Snorkel Ring - IN\n23. Main Ring - IN\n24. Reserve Ring - IN\n25. Landing Bag switch - AUTO\n26. Control Fuel - CHECK\n      a. Auto Fuel - 100%\n      b. Manual Fuel - 100%\n27. Rate of Descent - 0 FT/SEC\n28. Altimeter - CHECK\n29. Satellite clock\n      a. Time of Day\n      b. Time from launch - ZERO\n      c. Time to Retrograde\n30. Attitude/Rate ind. - CHECK\n      a. Rate indicators - CENTER\n      b. Attitude indicators - CHECK\n31. Time Zero Cover - REMOVE\n32. Cabin pressure - CHECK\n33. Cabin Air temp - CHECK\n34. Suit Env. Indicator - CHECK\n35. Oxygen Qunatity - CHECK\n      a. Primary - 100%\n      b. Secondayr - 100%\n36. Suit Fan switch - NORM\n37. Cabin Fan switch - NORM\n38. DC Volts knob - MAIN\n39. ASCS AC Bus - NORM\n40. Stby Btry switch - ON\n41. Isol Btry switch - STBY\n42. Inlet Valve Pwr switch - NORM\n43. Audio Bus switch - NORM\n44. AC voltmeter: 150 VOLTS\n45. VOX Pwe switch - OFF\n46. UHF DF switch - NORM\n47. UHF select switch - HI PWR\n48. Transmit switch - OFF\n49. Beacon switch - GRND\n50. All Audio Tone switches - ON\n51. Warning Lights switch - BRIGHT\n52. All switch fuses - NO. 1 POSITION\n53. Emer O2 switch - NORM\n54. Suit Temp selector - TO MARK\n55. Cabin Temp selector - TO MARK\n56. Inverter Temp selector - TO MARK","Steps":[],"Images":[]}

=== 343GuiltySpark-04/DefaultChecklists/Mercury/SystemsPreDark/checklist.json
{
    "Group": "SYSTEMS",
    "Images": [],
    "Name": "PRE-DARK",
    "ProjectName": "SystemsPreDark",
    "Side": 1,
    "SortPriority": 50,
    "Spacecraft": 3,
    "Steps": [],
    "checklistText": "1. Check that the flashlight work [T]\n2. Cabin Light swith - BOTH\n3. Photo Lights - OFF\n4. Red filters on cabin light [Click on the lights]\n5. Red scope filter - ON\n6. Warning lights - DIM\n7. Thruster warmup procedure\n (a) Go to MP mode (manual thrusters)\n      Pitch UP followed by pitch DOWN\n      Roll RIGHT followed by roll LEFT\n      Yaw RIGHT followed by yaw LEFT\n\n (b) Go to FBW (Hi and Lo thrusters)\n      Shurt-burst pitch UP and DOWN - full stick travel\n      Shurt-burst roll RIGHT and LEFT - full stick travel\n      Shurt-burst yaw RIGHT and LEFT - full stick travel\n\n (c) Go to ASCS mode and check for proper attitude\n      Orientation and holding within limits\n\n8. After entry into dark side, filters - as desired"
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/Backup13VerifyCouchConfig/checklist.json
{
  "Spacecraft": 0,
  "ProjectName": "Backup13VerifyCouchConfig",
  "Group": "BACKUP CREW PRELAUNCH",
  "Name": "VERIFY COUCH CONFIGURATION",
  "Side": 0,
  "SortPriority": 53,
  "checklistText": "VERIFY COUCH CONFIGURATION\r\n\r\n\tMDC assist bar – extd & locked\r\n\tHeadrests – soft suit position\r\n\tTHC armrest in launch position & locked\r\n\tIndb arm rests – stowed & contr locked\r\n\tCouches – launch/entry position (Y-Y\r\n\t\tstruts extd & locked)\r\n\tSeat pans - 85° position & locked\r\nO2/comm umb – stowed\r\nHarnesses & restraints – extd & laid aside\r\nCouch stab brace – stowed\r\nEgress CM\r\n\r\n\r\n\r\n\r\n",
  "Steps": [
    {
      "Program": 0,
      "Type": 0,
      "SetID": 0,
      "ToPosID": 0,
      "Text": "Toggle seats to normal launch config (visible)"
    }
  ],
  "Images": []
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/EPS_PrepDPSBurn/checklist.json
{
    "Group": "EPS",
    "Images": [],
    "Name": "Prepare DPS BURN",
    "ProjectName": "EPS_PrepDPSBurn",
    "Side": 1,
    "SortPriority": 1203,
    "Spacecraft": 1,
    "Steps": [],
    "checklistText": "<size=21>EPS PREPARATION FOR DPS BURN</size>\r\n\r\n1.\tPerform EPS Basic (Unstaged), except:\r\n\r\nPanel 11:\r\n\tCB EPS: INV 1 - close\r\n\r\nPanel 14:\r\n2.\tCheck a-c voltage from inverter No. 1:\r\n\tEPS:\r\n\t\tPOWER/TEMP MON sel - AC BUS\r\n\t\tINVERTER ew - 1\r\n\t\tVOLTS ind - green band\r\n\r\n\t\tCAUTION\r\n\r\n\tTwenty minutes before start of DPS burn,\r\n\tascent batteries must be placed on-line\r\n\tin parallel with descent batteries. CB\r\n\tEPS: CROSS TIE BAL LOADS (2) must remain\r\n\tclosed until just before start of burn.\r\n\r\n3.\tPlace both ascent batteries on line:\r\n\tEPS:\r\n\t\tPOWER/TEMP MON sel - BAT 5\r\n\t\tVOLTS ind - 31, 5 to 37.2 vdc\r\n\t\tAMPS ind - 0 amps\r\n\t\tBAT 5 NORMAL LMP FEED sw - ON; tb - gray\r\n\t\tVOLTS ind - 28.0 to 32.5 vdc\r\n\t\tAMPS ind - TBD\r\n\t\tPOWER/TEMP MON sel - BAT 6\r\n\t\tVOLTS ind - 31.5 to 37.2 vdc\r\n\t\tAMPS ind - 0 amps\r\n\t\tBAT 6 NORMAL CDR FEED sw - ON; tb - gray\r\n\t\tVOLTS ind - 28.0 to 32.5 vdc\r\n\t\tAMPS ind - TBD\r\n\r\nPanel 14:\r\n4.\tCheck voltage of all six batteries:\r\n\tEPS:\r\n\t\tPOWER/TEMP MON sel - BAT 1\r\n\t\tVOLTS ind - 28.0 to 32.5 vdc\r\n\t\tRepeat check for BAT 2, 3, 4, 5, & 6\r\n\r\n5.\tCheck d-c voltage on both buses:\r\n\tEPS:\r\n\t\tPOWER/TEMP MON sel - LMP BUS\r\n\t\tVOLTS ind - 26.5 to 32.5 vdc\r\n\r\n6.\tEPS: POWER/TEMP MON sel - CDR BUS\r\n\r\n"
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/SystemsEPSDC/checklist.json
{
  "Spacecraft": 0,
  "ProjectName": "SystemsEPSDC",
  "Group": "SYSTEMS: EPS",
  "Name": "D-C Check",
  "Side": 1,
  "SortPriority": 40503030,
  "checklistText": "\t\tD-C Voltage-Amperage Check\r\n\r\nPanel 5:\r\n\tMN BUS TIE (2) - OFF (verify)\r\n\r\nPanel 3:\r\n\tFC 1 & 2 MNA tb (2) - gray\r\n\tFC 3 MNA tb - bp\r\n\r\n\tFC 1 & 2 MNB tb - bp\r\n\tFC 3 MNB tb (2) - gray\r\n\tDC IND sel - FC 1, 2, 3\r\n\t\tDC AMPS ind - record amps\r\n\tDC IND sel - MNA, B\r\n\t\tDC VOLTS ind - 26.5-31 vdc (record)\r\n\tDC IND sel - BAT BUS A, B, & BAT C\r\n\t\tDC VOLTS ind - 31.5-38.0 vdc\r\n\t\tDC AMPS ind - <3.0 amps\r\n\r\nPanel 101:\r\n\tSYS TEST (2) - 5B\r\n\t\tSYS TEST ind - 3.4-4.1 vdc\r\n\r\nPanel 2:\r\n\tIf LM PWR - CSM\r\n\t\tSYS TEST (2) - 7D\r\n\t\t\tSYS TEST ind - 0.5-3.2 vdc\r\n\r\n\r\n\t\t\tCAUTION\r\n\r\n\t\tDo not leave DC IND sel at PYRO\r\n\t\tBAT A (B) position any longer\r\n\t\tthan req to read DC VOLTS ind,\r\n\t\tor pyro bat chg will be depleted.\r\n\r\nPanel 3:\r\n\tDC IND sel - PYRO BAT A, B\r\n\t\tDC VOLTS ind - 36.5-37.5 vdc\r\n\tDC IND sel - MNA\r\n\r\n\r\n\r\n\r\n",
  "Steps": [],
  "Images": []
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/SystemCabinSuitPSICheck/checklist.json
{
    "Group": "SYSTEM CHECKS",
    "Images": [],
    "Name": "CABIN & SUIT PSI CHECK",
    "ProjectName": "SystemCabinSuitPSICheck",
    "Side": 1,
    "SortPriority": 1003,
    "Spacecraft": 0,
    "Steps": [],
    "checklistText": "<size=21>SYSTEMS & MONITORING CHECKS\nCabin and suit pressure check</size>\r\nIf cabin press >5.3:\r\n\t02 flow - 0.2 lb/hr\r\nIf 4.7 < cabin press < 5.3\r\n\tO2 flow - pegged lo or hi,  ~0.7 lb/hr stable\r\nEMERG CABIN PRESS vlv - BOTH\r\nSUIT CKT RET vlv - open (pull)\r\nRemove helmet and gloves and stow in PGA bag"
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/TnDPostDocking/checklist.json
{"Spacecraft":0,"ProjectName":"TnDPostDocking","Group":"T&D","Name":"POST DOCKING","Side":0,"SortPriority":606,"checklistText":"<size=21>POST DOCKING checklist</size>\r\nRATE - HIGH\nATT DB - MAX\nCOAS - OFF\ncb RCS LOGIC (2) - open (verify)\nTVC SERVI PWR #1 - OFF\nEMS MODE - STBY\nEMS FUNC - OFF\nBMAG MODE (3) - RATE 2 (verify)\nLM PWR - OFF (verify)\nTUNNE LIGHTS - ON\n\n","Steps":[],"Images":[]}
