=== 343GuiltySpark-04/DefaultChecklists/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Reentry Checklist schema",
    "type": "object",
    "additionalProperties": false,
    "required": ["Group", "Name", "ProjectName", "Side", "SortPriority", "Spacecraft", "Steps", "Images"],
    "properties": {
        "Group": {"type": "string"},
        "Name": {"type": "string"},
        "ProjectName": {"type": "string"},
        "Side": {
            "type": "integer",
            "minimum": 0,
            "maximum": 1
        },
        "SortPriority": {"type": "integer"},
        "Spacecraft": {
            "type": "integer",
            "minimum": 0,
            "maximum": 3
        },
        "Steps": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": ["Program", "SetID", "Text", "ToPosID", "Type"],
                "properties": {
                    "Program": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 3
                    },
                    "SetID": {
                        "type": "integer"
                    },
                    "Text": {
                        "type": "string"
                    },
                    "ToPosID": {
                        "type": "integer"
                    },
                    "Type": {
                        "type": "integer"
                    }
                }
            }
        },
        "Images": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Position": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["x", "y"],
                        "properties": {
                            "x": {
                                "type": "number"
                            },
                            "y": {
                                "type": "number"
                            }
                        }
                    },
                    "Size": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["x", "y"],
                        "properties": {
                            "x": {
                                "type": "number"
                            },
                            "y": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "checklistText": {
            "type": "string"
        }
    }
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/LMInterfaceEVALMActiveDocking/checklist.json
{
    "Group": "LM INTERFACE & EVA",
    "Images": [],
    "Name": "LM Active Docking With CSM",
    "ProjectName": "LMInterfaceEVALMActiveDocking",
    "Side": 0,
    "SortPriority": 710,
    "Spacecraft": 0,
    "Steps": [],
    "checklistText": "LM Active Docking With CSM\r\n\r\n1.\tThe following are req\r\n\t\tCOAS - installed\r\n\t\tDocking trgt - installed\r\n\r\n2.\tConfigure CSM for docking\r\nPANEL 1:\t\n\t\tTHC PWR - on (up)\r\n\t\tTHC PWR DIR (both) - MNA/MNB\r\n\t\tSC CONT - CMC\r\n\t\tCMC MODE - HOLD\r\n\t\tBMAG MODE (3) - RATE 2\r\nPANEL 8:\n\t\tAUTO RCS (16) - MNA or MNB\r\nPANEL 1:\n\t\tMAN ATT (3) - RATE CMD\r\n\t\tTHC - ARMED\r\n\t\tRHC (both) - ARMED\r\n\t\tATT DBD - MIN\r\n\t\tRATE - LO\r\nPANEL 2:\n\t\tEXT RUN/EVA LT - on (up)\r\n\t\tCOAS - installed\r\nPANEL 8:\n\t\tcb DOCK PROBE (2) - close\r\nPANEL 2:\n\t\tPROBE RETR (2) - OFF\r\nPANEL 8:\n\t\tcb SECS ARM (2) - close\r\n\t\tSECs LOGIC (both) - on (up)\r\n\t\tSECS PYRO ARM (2) - on (up)\r\nPANEL 2:\n\tPROBE EXTD/REL - EXTD/REL\r\n\t\tPROBE EXTD/REL tb (2) - gray\r\n\r\n3.\tMon LM closing mnvrs\r\n\tBefore capture: \r\n\t\tCMC MODE - FREE\r\n\r\n4.\tInit capture latch & retraction\r\n\t\tPROBE EXTD/REL - RETRACT\r\n\t\tPROBE EXTD/REL tb (2) - mon\r\n\r\n5.\tSafe docking system\r\n\t\tPROBE EXTD/REL - OFF\r\n\t\tPROBE RETR (2) - OFF\r\n\t\tEXT RUN/EVA LT - OFF\r\n\t\tEXT RNDZ LT - off (ctr)\r\n\t\tCOAS - off\r\nPANEL 8:\n\t\tcb DOCK PROBE (2) - open\r\n\t\tSECS PYRO ARM (2) - SAFE\r\n\t\tSECS LOGIC (both) - open\t"
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/Emer_Abort1B/checklist.json
{
  "Spacecraft": 0,
  "ProjectName": "Emer_Abort1B",
  "Group": "ABORT",
  "Name": "Abort Mode 1B",
  "Side": 0,
  "SortPriority": 9000002,
  "checklistText": "\t\tMode 1B LES Abort (00:42 - 01:56)\r\n\r\n\r\n\t1\tAbort initiation\t\t\tX\r\n\t\t\tauto or man\t\t\t\tX\r\n\t\t\t THC - CCW\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\tXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n\tX\r\n\tX\tCM/SM SEP (both) - on\r\n\tX\t (up)\r\n\tX\r\n\tXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\tBECO (auto)\t\t\t\tX Request grd\r\n\t\t\t\t\t\t\t\t\tX  cmd BECO\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tEvnt Tmr rset &\t\t\tX\r\n\t\t counting up (auto)\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tCM/SM deadface (auto)\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tSM C/W lts - on\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tMASTER ALARM pb/lt -\t\tX\r\n\t\t\ton\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tCM RCS press\t\t\t\tX\r\n\t\t\t(auto)\t\t\t\t\tX\r\n\t\tRCS cont trnfr (auto)\t\tX\r\n\t\t\t\t\t\t\t\t\tX\t\r\n00:00.1\t\tCM/SM sep (auto)\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tLE motor fire  (auto)\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n00:01\t\tSCS/RCS enbl (auto)\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n00:01.8\t\tCM/SM sep pyro dead-\tX\r\n\t\t face (auto)\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\tXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n\tX\r\n00:05X If abort init with\r\n\tX  CM/SM SEP (both) or\r\n\tX  BU req for any auto\r\n\tX  evnt\r\n\tX\r\n\tX\tEVNT TMR RSET - RSET\r\n\tX\r\n\tX\tEVNT TMR START - START\r\n\tX\r\n\tX\tCM RCS PRESS - on (up)\r\n\tX\r\n\tX\tRCS TRNFR - CM\r\n\tX\r\n\tX\tLES MOT FIRE pb - push\r\n\tX\r\n\tX\tRCS CMD - ON\r\n\tX\r\n\tXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n\t\t\t\t\t\t\t\t\tX\r\n00:11\t\tCanard deploy (auto)\tX CNRD DPLY pb - push\r\n\t\t\t\t\t\t\t\t\tX\r\n\t2\tC/W CSM - CM\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t3\tMASTER ALARM pb/lt - \t\tX\r\n\t\t\tpush\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n00:14\t\tELS logic arm (auto)\tX ELS LOGIC - on (up)\r\n\t\t\t\t\t\t\t\t\tX\r\n24K'\t\tLES TWR jett (auto)\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\ta.\tDocking ring sep\t\tX CSM/LM FNL SEP\r\n\t\t\t\t\t\t\t\t\tX\t(both) - on (up)\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tb.\tTWR attach nuts\t\tX TWR JETT\r\n\t\t\tdetonate\t\t\t\tX\t(both) - on (up)\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tc.\tSCS RCS disable\t\t\tX RCS CMD - OFF\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\td.\tTWR jett mot fire\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tApex cover jett (auto)\t\tX APEX COVER JETT\r\n\t\t\t\t\t\t\t\t\tX\tpb - push\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tDrogue chutes deploy\t\tX DROG DPLY pb - push\r\n\t\t\t(auto)\t\t\t\t\tX\t(2 sec after\r\n\t\t\t\t\t\t\t\t\tX\tapex cover jett)\r\n\t\t\t\t\t\t\t\t\tX\r\n23.5K'\t4 \tMon CAB PRESS ind -\tX If not incr by 17K'\r\n\t\t\tstarts incr\t\t\t\tX\trh CAB PRESS\r\n\t\t\t\t\t\t\t\t\tX\t\tRELF vlv -\r\n\t\t\t\t\t\t\t\t\tX\t\tDUMP (safety\r\n\t\t\t\t\t\t\t\t\tX\t\tlatch off)\r\n\t\t\t\t\t\t\t\t\tX If still no incr\r\n\t\t\t\t\t\t\t\t\tX\tCAB PRESS DUMP\r\n\t\t\t\t\t\t\t\t\tX\t vlv - open\r\n\t\t\t\t\t\t\t\t\tX\t (CCW)\r\n\t\t\t\t\t\t\t\t\tX\r\n10K'\t\tMn chutes & VHF\t\tX\r\n\t\t\trecovery ant deploy\t\tX\r\n\t\t\t(auto)\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t5\tMN DPLY pb - push\t\t\tX\r\n\t\t\t(within 1 sec)\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\tCAUTION\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tCM PRPLNT DUMP should\t\tX\r\n\t\tbe init immediately\t\t\tX\r\n\t\tafter mn chute dis-\t\t\tX\r\n\t\treefing. If mn or\t\t\tX\r\n\t\tpyro bus lost, use RHCs\t\tX\r\n\t\tfor burn, not CM PRPLNT\tX\r\n\t\tDUMP sw.\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t6\tCAB PRESS RELF vlv (2)\t-\tX\r\n\t\t\tCLOSE (safety latch\t\tX If CAB PRESS DUMP\r\n\t\t\toff)\t\t\t\t\t\tX\tvlv used to\r\n\t\t\t\t\t\t\t\t\tX\tequalize ΔP, CAB\r\n\t\t\t\t\t\t\t\t\tX\tPRESS DUMP vlv -\r\n\t\t\t\t\t\t\t\t\tX\tclose (CW)\t\r\n\t\t\t\t\t\t\t\t\tX\r\n\t7\tCM PRPLNT DUMP - on (up)\tX\r\n\t\t\t(dump burn is audible)\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t8\tRCS IND sel - CM 1\t\t\tX RCS IND sel - CM 2\r\n\t\t\tCM RCS He PRESS ind -\tX CM RCS He PRESS\r\n\t\t\t decr\t\t\t\t\tX\tind - decr\r\n\t\t\t\t\t\t\t\t\tX\tIf not decr or\r\n\t\t\t\t\t\t\t\t\tX\tRCS jets not\r\n\t\t\t\t\t\t\t\t\tX\tfiring\r\n\t\t\t\t\t\t\t\t\tX\t\tRHC (both) -\r\n\t\t\t\t\t\t\t\t\tX\t\tFire all RCS\r\n\t\t\t\t\t\t\t\t\tX\t\tjets (except\r\n\t\t\t\t\t\t\t\t\tX\t\tplus pitch)\r\n\t\t\t\t\t\t\t\t\tX\t\tuntil\r\n\t\t\t\t\t\t\t\t\tX\t\tprplnts\r\n\t\t\t\t\t\t\t\t\tX\t\tare depleted\r\n\t\t\t\t\t\t\t\t\tX\r\n\t9\tSet up entry comm\t\t\tX\r\n\t\t\tVHF ANT - RECY\t\t\tX\r\n\t\t\tVHF AM A - SIMPLEX\t\tX\r\n\t\t\tVHF BCN - ON\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tXmit voice\t\t\t\t\tX\r\n\t\t\t(VHF AM) reporting\t\tX\r\n\t\t\t Position\t\t\t\tX\r\n\t\t\t Mn chutes\t\t\t\tX\r\n\t\t\t  disreefed\t\t\t\tX\r\n\t\t\t Splash err\t\t\t\tX\r\n\t\t\t Crew status\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t10\tCrew couch struts (4) -\t\tX\r\n\t\t\tunlock\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t11\tGrd track determination\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\ta.\tKey V37E 21E\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tb.\tFL V04 N06\t\t\t\tX\r\n\t\t\t Option code 00002\t\tX\r\n\t\t\t CMC assumed option\t\tX\r\n\t\t\t  0000X\t\t\t\t\tX\r\n\t\t\t   Verify\t\t\t\tX\r\n\t\t\t    R2 = 00001\t\t\tX\r\n\t\t\t     PRO\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tc.\tFL V06 N34\t\t\t\tX\r\n\t\t\t Get Lat Long\t\t\tX\r\n\t\t\t   00XXX. HRS\t\t\tX\r\n\t\t\t   000XX. MIN\t\t\tX\r\n\t\t\t   0XX.XX SEC\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\tAccept\tPRO\t\t\t\tX\r\n\t\t\tReject\tKey V25E\t\tX\r\n\t\t\t\tLoad\t\t\t\tX\r\n\t\t\t\t desired\t\t\t\tX\r\n\t\t\t\t GET Lat\t\t\tX\r\n\t\t\t\t Long\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\td.\tFL V06 N43\t\t\t\tX\r\n\t\t\t Lat (+N)\t\t\t\tX\r\n\t\t\t  XXX.XX DEG\t\t\tX\r\n\t\t\t Long (+E)\t\t\t\tX\r\n\t\t\t  XXX.XX DEG\t\t\tX\r\n\t\t\t Alt XXX.X NM\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t12\tWhen prplnt dump burn\t\tX\r\n\t\t\tcompleted\t\t\t\tX\r\n\t\t\t CM PRPLNT PURG - on\tX\r\n\t\t\t  (up) (purge is\t\t\tX CM RCS He DUMP pb -\r\n\t\t\t   audible)\t\t\t\tX  push\r\n\t\t\t\t\t\t\t\t\tX If RHC (both) used\r\n\t\t\t\t\t\t\t\t\tX  for prplnt dump\r\n\t\t\t\t\t\t\t\t\tX  burn\r\n\t\t\t\t\t\t\t\t\tX\tRHC (both) -\r\n\t\t\t\t\t\t\t\t\tX\t Fire all jets\r\n\t\t\t\t\t\t\t\t\tX\t  (except plus pitch)\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t13\tCAB PRESS RELF vlv (2)\t- \tX\r\n\t\t  BOOST/ENTR (safety\t\tX If CAB PRESS DUMP\r\n\t\t  latch off)\t\t\t\t\tX   vlv used to\r\n\t\t\t\t\t\t\t\t\tX   equalize ΔP, CAB\r\n\t\t\t\t\t\t\t\t\tX   PRESS DUMP vlv -\r\n\t\t\t\t\t\t\t\t\tX   open (CCW)\r\n\t\t\t\t\t\t\t\t\tX\r\n\t14\tcb FLT/PL BAT BUS A, B &\tX\r\n\t\t BAT C (3) - close\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t15\tcb FLT/PL MNA - open\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t16\tcb FLT/PL MNB - open\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t17\tcb RAD HTRS OVLD\t\t\tX\r\n\t\t (2) - open\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t18\tcb SPS PITCH (2) - open\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t19\tcb SPS YAW (2) - open\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n3K'\t20\trh CAB PRESS RELF vlv -\tX\r\n\t\t DUMP (safety latch\t\t\tX\r\n\t\t off)\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t21\tFLOOD FIXED - POST LDG\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t22\tFLOOD DIM - 1 or 2\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n800'\t23\tCAB PRESS RELF vlv (2)-X\r\n\t\t CLOSE (safety latch\t\tX If CAB PRESS DUMP\r\n\t\t\toff)\t\t\t\t\t\tX   vlv used to\r\n\t\t\t\t\t\t\t\t\tX   equalize ΔP, CAB\r\n\t\t\t\t\t\t\t\t\tX   PRESS DUMP vlv -\r\n\t\t\t\t\t\t\t\t\tX   close (CW)\r\n\t\t\t\t\t\t\t\t\tX\r\n\t24\tELS LOGIC - on (up)\t\t\tX\r\n\t\t\t(verify)\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t25\tCM RCS PRPLNT (both) -\t\tX\r\n\t\t\tOFF\t\t\t\t\t\tX\r\n\t\t\t CM RCS PRPLNT tb\t\tX\r\n\t\t\t  (both) - bp\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t26\tDIRECT O2 vlv - OPEN\t\tX\r\n\t\t\t(CCW)\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t27\tMN BUS TIE (2) - OFF\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\t\tCAUTION\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t\tMN BUS TIE sw must be\t\tX\r\n\t\tleft in OFF position\t\tX\r\n\t\tto ensure that bats\t\t\tX\r\n\t\tA, B, & C are used to\t\tX\r\n\t\tpwr postlanding sys\t\t\tX\r\n\t\tonly, & to prevent\t\t\tX\r\n\t\tbat shorting caused by\t\tX\r\n\t\twater entering CM\t\t\tX\r\n\t\tfeed-thru conn\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t28\tcb BAT RLY BUS (2) -\t\tX\r\n\t\t\topen\t\t\t\t\tX\r\n\t\t\t\t\t\t\t\t\tX\r\n\t29\tPostlanding check\t\t\tX\r\n\n\n\n\n\n",
  "Steps": [],
  "Images": []
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/StagingAPSPressurization/checklist.json
{
    "Group": "STAGING",
    "Images": [],
    "Name": "APS PRESSURIZATION",
    "ProjectName": "StagingAPSPressurization",
    "Side": 1,
    "SortPriority": 1520,
    "Spacecraft": 1,
    "Steps": [],
    "checklistText": "APS PRESSURIZATION & CHECKOUT\r\n\r\n1.\tControls - MPS Basic (Staged)\r\n\r\n2.\tHELIUM MON sel - PRESS 1\r\n\tMPS: HELIUM ind 2800 psia to 3500 psia\r\n\r\n3.\tHELIUM MON sel - PRESS 2\r\n\tMPS: HELIUM ind - 2800 to 3500 psia\r\n\r\n4.\tED:\r\n\t\tASC He SEL sw - BOTH\r\n\t\tMASTER ARM sw - ON\r\n\t\tASC He PRESS sw - FIRE\r\n\t\tMASTER ARM - OFF\r\n\r\n5.\tPRPLNT TEMP/PRESS MON sw - ASC\r\n\tMPS:\r\n\t\tFUEL TEMP ind - 50\u00c2\u00b0 to 90\u00c2\u00b0 F\r\n\t\tOXID TEMP ind - 50\u00c2\u00b0 to 90\u00c2\u00b0 F\r\n\t\tFUEL PRESS ind - 172 to 203 psia\r\n\t\tOXID PRESS ind - 172 to 203 psia\r\n\r\n6.\tHELIUM MON sel - PRESS 2\r\n\tMPS: HELIUM ind - 2700 to 3450 psia\r\n\tHELIUM MON sel PRESS 1\r\n\tMPS: HELIUM ind - 2700 to 3450 psia"
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/StagingDPSSupCritHeVent/checklist.json
{
    "Group": "STAGING",
    "Images": [],
    "Name": "DPS SUPCRIT He VENT",
    "ProjectName": "StagingDPSSupCritHeVent",
    "Side": 1,
    "SortPriority": 1510,
    "Spacecraft": 1,
    "Steps": [],
    "checklistText": "DPS SUPERCRITICAL He VENTING (LUNAR SURFACE ONLY)\r\n\r\n\tDPS Propellant Tank Venting is\r\n\tprerequisite to this procedure \r\n\r\n1.\tVent supercritical helium:\r\n\r\nPANEL 1:\r\n\t\tHELIUM MON sel - SUPERCRIT PRESS\r\n\t\tPRPLNT TEMP/PRESS MON sw - DES 1\r\nPANEL 8:\r\n\t\tDES PROPUL:\r\n\t\t\tFUEL VENT sw - OPEN: tb - gray\r\n\t\t\tOXID VENT sw - OPEN: tb - gray\r\nPANEL 1:\r\n\t\tDES He REG 1 sw - OPEN: tb - gray\r\n\t\tDES He REG 2 se - OPEN: tb - gray\r\nPANEL 8:\r\n\t\tCB PROPUL: DES He REG/VENT - open\r\n\r\nRemarks:\r\nFUEL VENT latching valve is open when tb - gray\r\nOXID VENT latching valve is open when tb - gray\r\nREG 1 & 2 SOV's and vent velves will be left open to\r\ninsure that descent supercritical helium, fuel and\r\noxidizer tanks will be at minimum pressure when ascent\r\nengine FITH occurs.\r\n\t\t\r\n2.\tVerify supercritical helium pressure decreasing"
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/LunarAscentRendezvousSimplified/checklist.json
{
    "Group": "LUNAR ASCENT",
    "Images": [],
    "Name": "Simplified Rendezvous",
    "ProjectName": "LunarAscentRendezvousSimplified",
    "Side": 0,
    "SortPriority": 320,
    "Spacecraft": 1,
    "Steps": [],
    "checklistText": "Simplified Rendezvous\r\n\r\nRemarks:\r\nThis rendezvous method uses a simplified approach\r\nwhere P30 (Externdal dV) is used to plan the prethrust\r\nfor CSI and TPI burns with input from Mission Control, \r\ninstead of P32.\r\nThe burns are executed using P41 (RCS Burn).\r\n\tIn reality, P32 and P3X is used to plan the burns \r\nwith input from Mission Control, and P41 is used to \r\nexecute the burns. P3Xs is still under development but \r\nhas a similar approach. \r\nThis method will soon be added to the simulator.\r\n\r\nUse P20 to track the CSM, and the AGC P79 for the\nCSM to track the LM.\n\r\nCoelliptic Sequence Initiation (CSI)\r\n\tThe CSI burn will circulate the orbit.\r\n\r\n1.\tTo plan the burn with MCC, use the\r\n\tradio and REQUEST CSI.\r\n\r\n2.\tWhen MCC communicates the TIG and dV parameters:\r\n\tChecklist: MPS/P30 EXTERNAL dV\r\n\r\n3.\tWhen 2. is complete:\r\n\tChecklist: MPS/P41 - RCS THRUST\r\n\r\n\r\nTerminal Phase Initiation (TPI)\r\n\tThe simplified TPI burn will set you on a rendezvous\r\n\ttrajectory with the CSM, using a hohmann transfer.\r\n\r\n1.\tTo plan the burn with MCC, use the\r\n\tradio and REQUEST TPI.\r\n\r\n2.\tWhen MCC communicates the TIG and dV parameters:\r\n\tChecklist: MPS/P30 EXTERNAL dV\r\n\r\n3.\tWhen 2. is complete:\r\n\tChecklist: MPS/P41 - RCS THRUST\n\n\nDOCKING"
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/SystemsPropulsionCMRCSMon/checklist.json
{
  "Spacecraft": 0,
  "ProjectName": "SystemsPropulsionCMRCSMon",
  "Group": "SYSTEMS: PROPULSION",
  "Name": "CM RCS CHECK",
  "Side": 1,
  "SortPriority": 40502030,
  "checklistText": "CM RCS Monitoring Check\r\n\r\n\t\tCM RCS PRPLNT tb (both) - gray\r\n\t\tRCS IND sel - CM 1, 2\r\n\t\t\tCM RCS He TEMP ind - 60°-90°\r\n\t\t\tPrior to CM RCS activation\r\n\t\t\t\tCM RCS He PRESS ind - 4100-4200 psia\r\n\t\t\t\tCM RCS MANF PRESS ind - 80-105 psia\r\n\r\n\r\n\r\n\t\tAfter CM RCS activation\r\n\t\t\tCM RCS He PRESS ind - stab at 3300-\r\n\t\t\t\t3500 psia ≈15 min after activation\r\n\t\t\tCM RCS MANF PRESS ind - 287-302 psia\r\n\r\n\r\n\r\n",
  "Steps": [],
  "Images": []
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/SystemsEPSFCPowerPlant/checklist.json
{
  "Spacecraft": 0,
  "ProjectName": "SystemsEPSFCPowerPlant",
  "Group": "SYSTEMS: EPS",
  "Name": "FC Power Plant",
  "Side": 1,
  "SortPriority": 40503020,
  "checklistText": "\t\tFC Power Plant Check\r\n\r\nPanel 3:\r\n\t\tFC HTRS (all) - on (up)\r\n\r\n\t\tFC REACS tb (all) - gray\r\n\t\tFC IND sel - 1, 2, 3\r\n\t\t\tFC H2 FLOW ind - 0.03-0.15 lb/hr\r\n\t\t\tFC O2 FLOW ind - 0.25-1.2 lb/hr\r\n\t\t\tFC SKIN TEMP ind - 390째-450째F\r\n\r\n\t\t\tFC COND EXH TEMP ind - 150째-175째F\r\n\t\t\tFC pH HI tb - gray\r\n\r\n\t\tFC RAD TEMP LO tb - gray\r\n\r\n\t\t\r\n",
  "Steps": [],
  "Images": []
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/AlignmentsGNP51/checklist.json
{
  "Spacecraft": 0,
  "ProjectName": "AlignmentsGNP51",
  "Group": "G&N ALIGNMENTS",
  "Name": "(P51) IMU Orientation",
  "Side": 1,
  "SortPriority": 41401010,
  "checklistText": "(P51/P53) IMU Orientation Determination\r\n\r\n\tCMC - on (req)\r\n\tISS - on (req)\r\n\tSCS - on (desired)\r\n\r\nPanel 7:\r\n\tLOGIC 2/3 PWR - on (up) (req if no SCS)\r\n\tOpt - on (req, P51)\r\n\tCOAS - calib (req, P53)\r\n\tAtt Cont (req)\r\n\r\n\r\n\tTotal Att Disp (req)\r\n\r\nPanel 2, 140:\r\n\r\n\t1 Key V37E 51E/53E\r\n\r\n\t\tPoss PROG alarm\r\n\t\r\n\t2 FL V50 N25\r\n\t\t00015 (trgt acq)\r\n\r\n\ta. Desired att cont mode\r\n\r\n\t\tMnvr to acq tgts, if necessary\r\n\t\r\nPanel 2, 140:\r\n\t\tPRO\r\n\t\tIf P51 go to 3\r\n\t\tIf P53 go to 4\r\n\r\n\tor b. To coarse align IMU to SC axes\r\n\t\tENTR (when att acpt)\r\n\t\tV41 N22 (coarse align)\r\n\t\t\tR, P, Y\t\t000.00 DEG\r\n\t\t\tNO ATT lt - on, then out\r\n\t\t\t\tRecycle 2\r\n\r\n\t\t(R53, Sighting Mark Routine)\r\n\r\n\t3 FL V51 (please mrk)\r\n\r\nPanel 122:\r\n\tOPT ZERO - OFF\r\n\tOPT MODE - MAN\r\n\tCtr trgt in SXT\r\n\tMARK (on trgt), go to 6\r\n\r\n\t(R56, Alternate LOS Sighting Mark Routine)\r\n\r\nPanel 2, 140:\r\n\t4 FL V06 N94\r\n\t\tSA\t\t\tXXX.XX DEG\r\n\t\tTA\t\t\tXX.XXX DEG\r\n\r\n\tAccept\tPRO\r\n\tReject\tKey V24E\r\n\t\tLoad desired SA & TA\r\n\r\n\r\n\t5 FL V53 (please mrk)\r\n\t\tRHC - ctr trgt in COAS reticle\r\n\r\n\t\tENTR, go to 6\r\n\r\n\t6 FL V50 N25\r\n\t\t00016 (term mrks)\r\n\r\n\tAccept\tPRO\r\n\r\nPanel 122:\r\n\tReject\tIf P51, MARK REJ pb - push\r\n\t\tReturn to 3\r\n\r\n\r\nPanel 2, 140:\r\n\t\tIf P53, ENTR, return to 5\r\n\r\n\t7 FL V01 N71\r\n\t\tTrgt code\t\t000XX\r\n\r\n\t\tAccept\tPRO\r\n\t\t\r\n\r\n\t\t\tPoss OPR ERR\r\n\t\t\t\tRecycles disp\r\n\r\n\r\n\tReject\tKey V21E\r\n\t\tLoad trgt code\r\n\r\n\tFor trgt 2 (trgt code â‰  00)\r\n\t\tP51, return to 3\r\n\t\tP53, return to 4\r\n\r\n\t8 FL V06 N88 (planet only)\r\n\t\tX, Y, Z\t\t.XXXXX\r\n\r\n\t\tAccept\tPRO\r\n\t\tReject\tKey V25E\r\n\t\t\tLoad desired data\r\n\r\n\t\tFor trgt 2\r\n\t\t\tP51, return to 3\r\n\t\t\tP53, return to 4\r\n\r\n\t\t\t(R54, Sighting Data Display Routine)\r\n\r\n\t9 FL V06 N05\r\n\t\tSighting angle diff\tXXX.XX DEG\r\n\r\n\t\tAccept\tPRO\r\n\t\tReject\tKey V32E, return to 2\r\n\r\n\t10 FL V37\r\n\t\tKey XXE\r\n\r\n\t11 If P51 and no P52\r\n\t\tOpt Pwr Down\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n",
  "Steps": [],
  "Images": []
}
