=== 343GuiltySpark-04/DefaultChecklists/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Reentry Checklist schema",
    "type": "object",
    "additionalProperties": false,
    "required": ["Group", "Name", "ProjectName", "Side", "SortPriority", "Spacecraft", "Steps", "Images"],
    "properties": {
        "Group": {"type": "string"},
        "Name": {"type": "string"},
        "ProjectName": {"type": "string"},
        "Side": {
            "type": "integer",
            "minimum": 0,
            "maximum": 1
        },
        "SortPriority": {"type": "integer"},
        "Spacecraft": {
            "type": "integer",
            "minimum": 0,
            "maximum": 3
        },
        "Steps": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": ["Program", "SetID", "Text", "ToPosID", "Type"],
                "properties": {
                    "Program": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 3
                    },
                    "SetID": {
                        "type": "integer"
                    },
                    "Text": {
                        "type": "string"
                    },
                    "ToPosID": {
                        "type": "integer"
                    },
                    "Type": {
                        "type": "integer"
                    }
                }
            }
        },
        "Images": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Position": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["x", "y"],
                        "properties": {
                            "x": {
                                "type": "number"
                            },
                            "y": {
                                "type": "number"
                            }
                        }
                    },
                    "Size": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["x", "y"],
                        "properties": {
                            "x": {
                                "type": "number"
                            },
                            "y": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "checklistText": {
            "type": "string"
        }
    }
}

=== 343GuiltySpark-04/DefaultChecklists/Mercury/EmerRetrograde/checklist.json
{
    "Group": "EMERGENCY PROCEDURES",
    "Images": [],
    "Name": "Retrograde",
    "ProjectName": "EmerRetrograde",
    "Side": 0,
    "SortPriority": 1020,
    "Spacecraft": 3,
    "Steps": [],
    "checklistText": "EMERGENCY PROCEDURES\n\nRETROGRADE\n\nIf the \"Retro Seq\" telelight fails to illuminate at retrograde\r\ntime, the retrograde sequence can be started by depressing the\r\nRetro Seq button or the Fire Retro button. Depressing\r\nthe Retro Seq button will start the normal retrograde\r\nsequence while depressing the Fire Retro button will fire the\r\nretrograde rockets. Use the Retro Att By-Pass switch to\r\nbypass correct retrograde during attitude failures.\r\n\r\nFAILURE TO ATTAIN RETROGRADE ATTITUDE\r\n1. Check attitude indicator and periscope to determine\r\n\tif capsule is in retrograde attitude.\r\n2. If capsule is in the retrograde attitude:\r\n\ta. Retro Att switch - BYPASS\r\n\tb. Fire Retro button - DEPRESS\r\n3.If the capsule is not in the retrograde attitude:\r\n\ta. Manual fuel handle - PUSH RATE COMD\r\n\tb. RSCS switch - RATE COMD\r\n\tc. ASCS switch - FLY-BY-WIRE\r\n\td. Use hand controller to position capsule in the\r\n\t\tretrograde attitude.\r\n\te. If attitude permission circuit is operating, the\r\n\t\tretrograde rockets will fire 30 seconds after\r\n\t\tinitiating retro sequence or as soon as the\r\n\t\tcapsule if in the retrograde attitude, if\r\n\t\tover 30 seconds.\r\n\r\nRETROGRADE PACKAGFE FAILS TO JETTISON\r\nThe retrograde package is jettisoned 60 seconds after retro\r\nfire is initiated.\r\nIf it fails:\r\n1. Jett Retro button - DEPRESS\r\n2. If Retrograde package does not jettison:\r\n\ta. Retro Jett fuse switch - NO. 2\r\n\tb. Emer Retro Jett fuse switch - NO.2\r\n3. Jett Retro button - DEPRESS\r\n\r\n\r\nASCS CANNOT MAINTAIN RE-ENTRY ATTITUDE\r\nIf ASCS does not reposition capsule to correct re-entry\r\nattitude when Attitude switch is set to RE-ENTRY:\r\n1. Manual fuel handle - PUSH RATE COMD\r\n2. RSCS switch - RATE COMD\r\n3. Retract Scope switch - MAN\r\n4. Use hand controller to position the capsule in the\r\n\tre-entry attitude.\r\n5. RSCS switch - AUTO\r\n6. Use periscope to see if ASCS will maintain re-entry\r\n\tattitude.\r\n7. If ASCS will maintain re-entry attitude:\r\n\tRetract Scope switch - AUTO.\r\n8. If ASCS will not maintain re-entry attitude:\r\n\ta. RSCS switch - RATE COMD\r\n\tb. As soon as the \".05g Switch\" telelight illuminates\r\n\t\tRetract Scope switch - AUTO.\r\n\tc. Check that RSCS initiates 7 degree/sec slow roll.\r\n\r\n\r\n"
}

=== 343GuiltySpark-04/DefaultChecklists/CommandModule/TnDCSMSep/checklist.json
{"Spacecraft":0,"ProjectName":"TnDCSMSep","Group":"T&D","Name":"CSM SEPARATION","Side":0,"SortPriority":603,"checklistText":"<size=21>CSM SEPARATION checklist</size>\r\nV49E\tF 06 22 (EXTRACT ATT)\ncb SECS LOGIC (2) - closed (verify)\ncb SECS ARM (2) - closed (verify)\nSECS LOGIC (2) - on (up)(verify)\nRCS CMD - ON\nSECS PYRO ARM (2) - ARM\nGDC ALIGN\nEMS FUNC - ΔV (verify)\nEMS MODE - NORMAL\n59:30\tStart DET\n59:50\tCMC MODE - AUTO\n59:58\tThurst +X and hold\n00:00\tCSM/LV SEP pb - push, hold, and release\n\tLV TANK PRESS - full scale low\n00:03\tTHC - release (ΔV .5 fps)\n\tSM RCS PRPLNT tb (8) - gray(verify)\n\tSM RCS He tb (8) - gray (verify)\n\tSM RCS SEC PRPLNT FUEL PRESS (4) - CLOSE\n\tFC REAC vlv - NORM","Steps":[],"Images":[]}

=== 343GuiltySpark-04/DefaultChecklists/Gemini/OrbitingCircOrbit/checklist.json
{
    "Group": "ORBITING",
    "Images": [],
    "Name": "CIRCULARIZE ORBIT",
    "ProjectName": "OrbitingCircOrbit",
    "Side": 0,
    "SortPriority": 32,
    "Spacecraft": 2,
    "Steps": [],
    "checklistText": "CIRCULARIZE ORBIT\nComputer:\n- Set Ap (core 57) and Pe (core 56) to your destination target.\n- Read time to Ap (core 73) and Pe (core 74)\n\nThe Hohmann Transfer:\nAt Apogee:\n- Burn so IVI's read zero\n\nAp Perigee:\n- Burn so IVI's read zero"
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/IntravehicularTransfer/checklist.json
{
    "Group": "ACTIVATION",
    "Name": "Intravehicular Transfer",
    "ProjectName": "IntravehicularTransfer",
    "Side": 0,
    "SortPriority": 110,
    "Spacecraft": 1,
    "Steps": [],
    "Images": [],
    "checklistText": "<size=21>INITIAL INTRAVEHICULAR TRANSFER TO LM/CSM</size>\r\n\n1.\tCM/LM are docked\n2.\tEqualize the pressure using LM tunnel hatch\n3.\tOpen hatch using the Tools menu\n4.\tPress F4 to switch between the active spacecrafts.\n"
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/EPS_PostDPSBurn/checklist.json
{
    "Group": "EPS",
    "Images": [],
    "Name": "Post DPS-Burn",
    "ProjectName": "EPS_PostDPSBurn",
    "Side": 1,
    "SortPriority": 1204,
    "Spacecraft": 1,
    "Steps": [],
    "checklistText": "<size=21>EPS CHECK, POST-DPS BURN</size>\r\n\r\nPanel 11:\r\n1.\tCB EPS: ASC ECA CONT - close\r\n\r\nPanel 16:\r\n2.\tCB EPS: ASC ECA CONT - close\r\n\r\nPanel 14:\r\n3.\tRemove ascent batteries from line:\r\n\tEPS:\r\n\t\tBAT 5 NORMAL LMP FEED sw - OFF/RESET: tb - bp\r\n\t\tBAT 6 NORMAL CDR FEED SW - OFF/RESET: tb - bp\r\n\r\n4.\tCheck voltage & current of descent batteries:\r\n\tEPS:\r\n\t\tPOWER/TEMP MOW sel - BAT 1\r\n\t\tVOLTS ind - 28.0 to 32.5 vdc\r\n\t\tAMPS ind - TBD\r\n\tRepeat for BAT 2, 3, & 4.\r\n\r\nPanel 11:\r\n5.\tCB EPS: ASC ECA CONT - open\r\n\r\nPanel 16:\r\n6.\tCB EPS: ASC ECA CONT - open\r\n\r\nPanel 14:\r\n7.\tCheck a-c voltage from inverter No. 1:\r\n\tEPS:\r\n\t\tPOWER/TEMP MON sel - AC BUS\r\n\t\tINVERTER sw - 1\r\n\t\tVOLTS ind - green band\r\n\t\tINVERTER SW - 2\r\n\t\tVOLTS ind - green band\r\n\t\tPOWER/TEMP MON sel - CDR BUS\r\n\r\nPanel 11:\r\n8.\tCB EPS: INV 1 - open"
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/StagingDPSPropTankVent/checklist.json
{
    "Group": "STAGING",
    "Images": [],
    "Name": "DPS PRPLNT VENTING",
    "ProjectName": "StagingDPSPropTankVent",
    "Side": 1,
    "SortPriority": 1501,
    "Spacecraft": 1,
    "Steps": [],
    "checklistText": "DPS PROPELLANT TANK VENTING\n\r\n1.\tControls - MPS Basic (Unstaged)\r\n\r\n2.\r\nPANEL 1:\r\n\tDES He REG 1 sw - CLOSE: tb - bp\r\n\tDES He REG 2 tb - bp\r\n\r\n3.\r\nPANEL 8:\r\n\tVent propellant tanks.\r\n\tDES PROPUL:\r\n\t\tOXID VENT - tb - gray\r\n\t\tFUEL VENT - tb - gray\r\n\tED:\r\n\t\tMASTER ARM sw - ON\r\n\t\tDES VENT sw - FIRE\r\n\t\tMASTER ARM sw - OFF\r\n\r\nPANEL 1:\r\n\tMPS:\r\n\t\tOXID & FUEL PRESS ind - verify fuel &\r\n\t\toxidizer pressure decreasing\r\n\t\tDES REG warn lt - on\r\n\r\n4.\r\n\tFor lunar-surface venting only -\r\n\tWhen MPS: OXID PRESS ind - 20 to 40 psia:\r\nPANEL 8:\r\n\tDES PROPUL: OXID VENT sw - CLOSE; tb-bp\r\n\tWhen MPS: FULE PRESS ind - <8 psia:\r\n\tDES PROPUL: FUEL VENT sw - CLOSE; tb-bp\r\n\r\n\r\n5.\tFor zero-g venting only -\r\n\tIf vent stops on its own or if pressure decrease\r\n\t<1 psia/10 sec:\r\nPANEL 11:\r\n\tCB S/C: ATT DIR CONT - close\r\nPANEL 5:\r\n\t+X TRANSL pb - push and hold\r\n\tWait 2 sec, then:\r\nPANEL 8:\r\n\tDES PRPUL:\r\n\t\tOXID VENT sw - OPEN; tb - gray\r\n\t\tFUEL VENT sw - OPEN; tb - gray\r\n\tTerminate translation after 10 sec:\r\nPANEL 5:\r\n\t+X TRANSL pb - release\r\nPANEL 1:\r\n\tWhen MPS: OXID PRESS ind reducing\r\nPANEL 8:\r\n\tDES PROPUL: OXID VENT sw - CLOSE; tb-bp\r\n\tWhen MPS: FULE PRESS ind - <8 psia:\r\n\tDES PROPUL: FUEL VENT sw - CLOSE; tb-bp"
}

=== 343GuiltySpark-04/DefaultChecklists/Gemini/PreFlightInteriorInspection/checklist.json
{
  "Spacecraft": 2,
  "ProjectName": "PreFlightInteriorInspection",
  "Group": "PRE-FLIGHT",
  "Name": "INTERIOR INSPECTION (T-90)",
  "Side": 0,
  "SortPriority": 0,
  "checklistText": "INTERIOR INSPECTION (T-90)\nApprox. T-90 minutes\n\nFuel Cell Section 1 - WARMUP\r\nFuel Cell Section 2 - WARMUP",
  "Steps": [],
  "Images": []
}

=== 343GuiltySpark-04/DefaultChecklists/LunarModule/PoweredDescentP66/checklist.json
{
    "Group": "LUNAR DESCENT",
    "Name": "P66 - LANDING PHASE",
    "ProjectName": "PoweredDescentP66",
    "Side": 0,
    "SortPriority": 204,
    "Spacecraft": 1,
    "Steps": [],
    "Images": [],
    "checklistText": "LANDING PHASE (ROD) PROGRAM (P66)\r\n\r\n1.\tObserve PROG ind - 66\r\n\r\n2.\tFL V06 N60\r\n\t\tR1 V (Forward)\tXXXX.X fps\r\n\t\tR2 H rate\t\tXXXX.X fps\r\n\t\tR3 H\t\tXXXXX ft\r\n\r\n3.\tMonitor descent:\r\n\tDES RATE sw - effect desired rate of descent.\r\n\t\r\n\tINPUT SETTINGS:\r\n\tUse the bound ROD axis (pos/neg) to modify rate of descent.\r\n\r\n\tIf manual attitude control:\r\n\t\tACA:\r\n\t\t\tSet S/C: ATTITUDE CONT: PITCH to DIR\r\n\t\t\tMaintain ATTITUDE\r\n\r\n\r\n\t\t\tWARNING\r\n\r\n\t\tDES QTY warn lt will not be accompanies\r\n\t\tby MASTER ALARM; therefore, crewman must\r\n\t\tmonitor MPS: FUEL & OXID QUANTITY ind.\r\n\r\n4.\tMonitor CMD THRUST ind\r\n\r\n5.\tIf manual throttle control is desired:\r\n\tENG THR CONTR: THR CONT sw - MAN\r\n\tTTCA - move up until CMD THRUST ind - 20%, and null descent rate.\r\n\tContinue descent.\r\n\r\n6.\tWhen forward & alteral velocities <XX fps:\r\n\tVEL lt - on\r\n\tALT lt - on\r\n\r\n7.\tMonitor touchdown:\r\nPanel 1,3:\r\n\tLUNAR CONTACT lt - on\r\n\tEng STOP pb/lt - push\r\n\t(skip) Stand by to abort stage if:\r\n\t\tLM tilt angle >XX\u00c2\u00b0\r\n\t\tLM tilt angle changing at >X\u00c2\u00b0/sec\r\n\r\n8.\tAfter LM is stabilized:\r\n\tENG THR CONT: ENG ARM sw - OFF\r\nPanel 3:\r\n\tS/C: PGNS sw - ATT HOLD\r\n\tACA - out of detent to deactivate RCA thrusters if required\r\n\tRecord LM attitude\r\n\r\n\tKey PRO\r\n\t\r\n\tWhen Lunar-stay decision is made:\r\n\tKey V37E 68E\r\n\r\n\r\n\r\n"
}
